#! /bin/bash

# Run from root repo directory.

build_dir=build-dir-show-bug
/bin/rm -rf $build_dir
mkdir $build_dir
cd $build_dir
cmake .. >& /dev/null && make -f CMakeFiles/demofail.dir/build.make CMakeFiles/demofail.dir/depend >& /dev/null
grep 'CMakeFiles/demofail.dir/ice_flux.F90.o: CMakeFiles/demofail.dir/ice_state.mod.stamp' ./CMakeFiles/demofail.dir/depend.make >& /dev/null
if [ $? -eq 0 ]; then
    echo WORKED
else
    echo DEP SCAN FAILED
fi
